server:
  port: 9007
spring:
  application:
    name: tensquare-split
  data:
    mongodb:
      host: 192.168.8.128
      port: 27017
      database: splitdb
    elasticsearch:
      cluster-nodes: 192.168.8.128:9300
      repositories:
        enabled: true